"""Finalize: merge schema, facts, and rules into knowledge_base.ml."""

from datetime import datetime, timezone
from pathlib import Path

from minilog.extract.session import load_session, save_session
from minilog.extract.steps.domains_writer import write_domains_md


def finalize(book_dir: Path) -> Path:
    """Merge schema.ml, facts.ml, and rules.ml into knowledge_base.ml."""
    state = load_session(book_dir)

    from minilog.extract.paths import kb_dir, artifacts_dir
    out = kb_dir(book_dir)
    arts = artifacts_dir(book_dir)

    # Read metadata from book root
    meta_path = book_dir / "metadata.txt"
    meta_lines = meta_path.read_text(encoding="utf-8") if meta_path.exists() else ""

    # Collect parts
    parts = []
    parts.append(f"% knowledge_base.ml — generated by minilog extract")
    parts.append(f"% Date: {datetime.now(timezone.utc).isoformat()}")
    parts.append(f"% Source: {book_dir.name}")
    if meta_lines:
        for line in meta_lines.strip().splitlines():
            parts.append(f"% {line}")
    parts.append("")

    # Schema (from kb/artifacts/)
    schema_path = arts / "schema.ml"
    if schema_path.exists():
        parts.append("% " + "=" * 60)
        parts.append("% Schema")
        parts.append("% " + "=" * 60)
        parts.append(schema_path.read_text(encoding="utf-8"))

    # Facts (from kb/artifacts/)
    facts_path = arts / "facts.ml"
    if facts_path.exists():
        parts.append("% " + "=" * 60)
        parts.append("% Facts")
        parts.append("% " + "=" * 60)
        parts.append(facts_path.read_text(encoding="utf-8"))

    # Rules (from kb/artifacts/)
    rules_path = arts / "rules.ml"
    if rules_path.exists():
        parts.append("% " + "=" * 60)
        parts.append("% Rules")
        parts.append("% " + "=" * 60)
        parts.append(rules_path.read_text(encoding="utf-8"))

    # Final file named after the book folder
    kb_path = out / f"{book_dir.name}.ml"
    kb_path.write_text("\n".join(parts) + "\n", encoding="utf-8")

    # Update domains.md with ontological profile
    _write_ontological_profile(book_dir, state)

    state["current_step"] = "finalized"
    save_session(book_dir, state)

    return kb_path


def _write_ontological_profile(book_dir: Path, state: dict) -> None:
    """Add ontological profile section to domains.md."""
    # First regenerate domains.md from session
    write_domains_md(book_dir)

    # Then append ontological profile
    from minilog.extract.paths import artifacts_dir
    domains_path = artifacts_dir(book_dir) / "domains.md"
    content = domains_path.read_text(encoding="utf-8")

    facts = state.get("extracted_facts", [])
    rules = state.get("generated_rules", [])

    # Count facts per domain
    schema = state.get("proposed_schema", {})
    pred_to_domain: dict[str, str] = {}
    for domain, preds in schema.items():
        for p in preds:
            pred_to_domain[p["functor"]] = domain

    facts_by_domain: dict[str, int] = {}
    for f in facts:
        if f.get("valid"):
            domain = pred_to_domain.get(f.get("predicate", ""), "unknown")
            facts_by_domain[domain] = facts_by_domain.get(domain, 0) + 1

    rules_by_domain: dict[str, int] = {}
    for r in rules:
        if r.get("valid"):
            domain = r.get("domain", "unknown")
            if not domain:
                name = r.get("name", "")
                domain = pred_to_domain.get(name, "unknown")
            rules_by_domain[domain] = rules_by_domain.get(domain, 0) + 1

    profile = [
        "",
        "## Ontological Profile",
        "",
        "| Domain | Facts | Rules |",
        "|--------|-------|-------|",
    ]
    all_domains = set(list(facts_by_domain.keys()) + list(rules_by_domain.keys()))
    for domain in sorted(all_domains):
        fc = facts_by_domain.get(domain, 0)
        rc = rules_by_domain.get(domain, 0)
        profile.append(f"| {domain} | {fc} | {rc} |")

    total_facts = sum(facts_by_domain.values())
    total_rules = sum(1 for r in rules if r.get("valid"))
    profile.append("")
    profile.append(f"**Total:** {total_facts} facts, {total_rules} rules")
    profile.append("")

    content += "\n".join(profile) + "\n"
    domains_path.write_text(content, encoding="utf-8")
